### ISSUE TITLE
dunt switch to java

### ISSUE THREAD

**Issue by TheInitializer** [Team865/FRC-2015#3]
at the open house yesterday I heard someone say you were thinking of switching back to java pls dont python is bae <333

**Comment by aerobit** [comment]
Python IS bae, but nobody knows python and I'm not the programmer next year :((((((((((((((((((((((((((((((((((((((((((((((9

It's gonna be java :sob:

**Comment by TheInitializer** [comment]
I know python and I'll be on your team next year...!
